### ISSUE TITLE
plugin preventing package building correctly in Appflow (XCode10, Cordova 9)

### ISSUE THREAD

**Issue by jcohenar123** [apache/cordova-plugin-compat#4]
I'm using ionic AppFlow and when trying to build a production package with XCode 10. I'm getting the following error:

```
Discovered saved plugin "cordova-plugin-compat". Adding it to the project
Installing "cordova-plugin-compat" for ios
Adding cordova-plugin-compat to package.json
Failed to restore plugin "cordova-plugin-compat" from config.xml. You might need to try adding it again. Error: Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
```

After reinstalling the plugin the error remains. Ionic team tells me this is due to plugin incompatibility with Cordova 9.

Would much appreciate your comments on this.

**Comment by janpio** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
